// App
export const APP_LOGIN = 'APP_LOGIN';

export const APP_INCORRECT_LOGIN = 'APP_INCORRECT_LOGIN';
export const APP_CORRECT_LOGIN = 'APP_CORRECT_LOGIN';

export const APP_BOOK_SUCCESSFUL_LOAD = 'APP_BOOK_SUCCESSFUL_LOAD';
export const APP_BOOK_FAILED_LOAD = 'APP_BOOK_FAILED_LOAD';

export const APP_MYPAGE_SUCCESSFUL_LOAD = 'APP_MYPAGE_SUCCESSFUL_LOAD';
export const APP_MYPAGE_FAILED_LOAD = 'APP_MYPAGE_FAILED_LOAD';
export const APP_MYPAGE_REQUESTS_SUCCESSFUL_LOAD = 'APP_MYPAGE_REQUESTS_SUCCESSFUL_LOAD';
export const APP_MYPAGE_REQUESTS_FAILED_LOAD = 'APP_MYPAGE_REQUESTS_FAILED_LOAD';
export const APP_MYPAGE_LASTVISITED_LOAD = 'APP_MYPAGE_LASTVISITED_SUCCESSFUL_LOAD';
export const APP_MYPAGE_REQUEST_FAILED_SET = 'APP_MYPAGE_REQUEST_FAILED_SET';

export const APP_USERPAGE_SUCCESSFUL_LOAD = 'APP_USERPAGE_SUCCESSFUL_LOAD';
export const APP_USERPAGE_FAILED_LOAD = 'APP_USERPAGE_FAILED_LOAD';
export const APP_USERPAGE_REQUEST_ACCESS = 'APP_USERPAGE_REQUEST_ACCESS';

export const APP_BRANCHES_LOAD = 'APP_BRANCHES_LOAD';

export const APP_MYPAGEUPDATE_SUCCESSFUL = 'APP_MYPAGEUPDATE_SUCCESSFUL';
export const APP_MYPAGEUPDATE_FAILED = 'APP_MYPAGEUPDATE_FAILED';

// Admin App
export const ADMIN_LOGIN = 'ADMIN_LOGIN';

export const ADMIN_INCORRECT_LOGIN = 'ADMIN_INCORRECT_LOGIN';
export const ADMIN_CORRECT_LOGIN = 'ADMIN_CORRECT_LOGIN';

export const ADMIN_BOOK_SUCCESSFUL_LOAD = 'ADMIN_BOOK_SUCCESSFUL_LOAD';
export const ADMIN_BOOK_FAILED_LOAD = 'ADMIN_BOOK_FAILED_LOAD';

export const ADMIN_BRANCHES_SUCCESSFUL_LOAD = 'ADMIN_BRANCHES_SUCCESSFUL_LOAD';
export const ADMIN_BRANCHES_FAILED_LOAD = 'ADMIN_BRANCHES_FAILED_LOAD';
export const ADMIN_BRANCHES_SUCCESSFUL_EDIT = 'ADMIN_BRANCHES_SUCCESSFUL_EDIT';
export const ADMIN_BRANCHES_FAILED_EDIT = 'ADMIN_BRANCHES_FAILED_EDIT';

export const ADMIN_REQUESTS_SUCCESSFUL_LOAD = 'ADMIN_REQUESTS_SUCCESSFUL_LOAD';
export const ADMIN_REQUESTS_FAILED_LOAD = 'ADMIN_REQUESTS_FAILED_LOAD';
export const ADMIN_REQUESTS_SUCCESSFUL_EDIT = 'ADMIN_REQUESTS_SUCCESSFUL_EDIT';
export const ADMIN_REQUESTS_FAILED_EDIT = 'ADMIN_REQUESTS_FAILED_EDIT';

export const ADMIN_USERPAGE_SUCCESSFUL_LOAD = 'ADMIN_USERPAGE_SUCCESSFUL_LOAD';
export const ADMIN_USERPAGE_FAILED_LOAD = 'ADMIN_USERPAGE_FAILED_LOAD';
export const ADMIN_USERPAGE_SUCCESSFUL_UPDATE = 'ADMIN_USERPAGE_SUCCESSFUL_UPDATE';
export const ADMIN_USERPAGE_FAILED_UPDATE = 'ADMIN_USERPAGE_FAILED_UPDATE';
export const ADMIN_USERPAGE_SUCCESSFUL_DELETE = 'ADMIN_USERPAGE_SUCCESSFUL_DELETE';
export const ADMIN_USERPAGE_FAILED_DELETE = 'ADMIN_USERPAGE_FAILED_DELETE';