export const APP_LOGIN = 'APP_LOGIN';

export const APP_INCORRECT_LOGIN = 'APP_INCORRECT_LOGIN';
export const APP_CORRECT_LOGIN = 'APP_CORRECT_LOGIN';

export const APP_BOOK_SUCCESSFUL_LOAD = 'APP_BOOK_SUCCESSFUL_LOAD';
export const APP_BOOK_FAILED_LOAD = 'APP_BOOK_FAILED_LOAD';

export const APP_MYPAGE_SUCCESSFUL_LOAD = 'APP_MYPAGE_SUCCESSFUL_LOAD';
export const APP_MYPAGE_FAILED_LOAD = 'APP_MYPAGE_FAILED_LOAD';
export const APP_MYPAGE_REQUESTS_SUCCESSFUL_LOAD = 'APP_MYPAGE_REQUESTS_SUCCESSFUL_LOAD';
export const APP_MYPAGE_REQUESTS_FAILED_LOAD = 'APP_MYPAGE_REQUESTS_FAILED_LOAD';
export const APP_MYPAGE_LASTVISITED_LOAD = 'APP_MYPAGE_LASTVISITED_SUCCESSFUL_LOAD';
export const APP_MYPAGE_REQUEST_FAILED_SET = 'APP_MYPAGE_REQUEST_FAILED_SET';

export const APP_USERPAGE_SUCCESSFUL_LOAD = 'APP_USERPAGE_SUCCESSFUL_LOAD';
export const APP_USERPAGE_FAILED_LOAD = 'APP_USERPAGE_FAILED_LOAD';
export const APP_USERPAGE_REQUEST_ACCESS = 'APP_USERPAGE_REQUEST_ACCESS';

export const APP_BRANCHES_LOAD = 'APP_BRANCHES_LOAD';

export const APP_MYPAGEUPDATE_SUCCESSFUL = 'APP_MYPAGEUPDATE_SUCCESSFUL';
export const APP_MYPAGEUPDATE_FAILED = 'APP_MYPAGEUPDATE_FAILED';
